# Project Pipeline Lab


## 1. Data loading
In this lab we will create pipelines for data processing on the [Titanic dataset](http://www.kaggle.com/c/titanic-gettingStarted/data).

The dataset is a list of passengers. The second column of the dataset is a “label” for each person indicating whether that person survived (1) or did not survive (0). Here is the Kaggle page with more information on the dataset:

You can grab the titanic data as follows:

    psql -h dsi.c20gkj5cvu3l.us-east-1.rds.amazonaws.com -p 5432 -U dsi_student titanic
    password: gastudents

In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

from sqlalchemy import create_engine
engine = create_engine('postgresql://dsi_student:gastudents@dsi.c20gkj5cvu3l.us-east-1.rds.amazonaws.com/titanic')

df = pd.read_sql('SELECT * FROM train', engine)

Have a look at the data using the info method:

- Are there numerical features?
- Are there categorical features?
- Which columns have missing data?
- Which of these are important to be filled?

In [ ]:
df.info()

## 2. Age

Several passengers are missing data points for age. Impute the missing values so that there are no “NaN” values for age as inputs to your model. Explore the distribution of age and decide how you are going to impute the data.

In [ ]:
df.Age.plot(kind = 'hist')

### 2.b: Age Transformer

Create a custom transformer that imputes the age values. Depending on how you have decided to impute missing values, this could involve:

- Selecting one or more columns
- Filling the NAs using Imputer or a custom strategy
- Scaling the Age values

In [11]:
from sklearn.pipeline import make_pipeline, make_union
from sklearn.preprocessing import Imputer, StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin

class ColumnSelector(BaseEstimator, TransformerMixin):
    def __init__(self, columns):
        self.columns = columns
    
    def transform(self, X, *_):
        if isinstance(X, pd.DataFrame):
            return pd.DataFrame(X[self.columns])
        else:
            raise TypeError("This transformer only works with Pandas Dataframes")
    
    def fit(self, X, *_):
        return self
    
cs = ColumnSelector('Age')

cs.transform(df).head()

Age
0  22.0
1  38.0
2  26.0
3  35.0
4  35.0

In [9]:
age_pipe = make_pipeline(ColumnSelector('Age'),
                         Imputer(),
                         StandardScaler())

age_pipe.fit_transform(df)[:5]

array([[-0.5924806 ],
       [ 0.63878901],
       [-0.2846632 ],
       [ 0.40792596],
       [ 0.40792596]])

## 3. Categorical Variables

`Embarked` and `Pclass` are categorical variables. Use pandas get_dummies function to create dummy columns corresponding to the values.

`Embarked` has 2 missing values. Fill them with the most common port of embarkment.

Feel free to create a GetDummiesTransformer that wraps around the get_dummies function.

In [17]:
df.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [18]:
df.Embarked = df.Embarked.fillna('S')

In [19]:
pd.get_dummies(pd.DataFrame(df['Embarked'].head()))

Embarked_C  Embarked_S
0         0.0         1.0
1         1.0         0.0
2         0.0         1.0
3         0.0         1.0
4         0.0         1.0

In [20]:
class GetDummiesTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, columns):
        self.columns = columns
    
    def transform(self, X, *_):
        if isinstance(X, pd.DataFrame):
            return pd.get_dummies(X[self.columns], columns = self.columns)
        else:
            raise TypeError("This transformer only works with Pandas Dataframes")
    
    def fit(self, X, *_):
        return self
    
gdt = GetDummiesTransformer(['Embarked'])
gdt.fit_transform(df.head())

Embarked_C  Embarked_S
0         0.0         1.0
1         1.0         0.0
2         0.0         1.0
3         0.0         1.0
4         0.0         1.0

In [21]:
one_hot_pipe = GetDummiesTransformer(['Pclass', 'Embarked'])

one_hot_pipe.fit_transform(df).head()

Pclass_1  Pclass_2  Pclass_3  Embarked_C  Embarked_Q  Embarked_S
0       0.0       0.0       1.0         0.0         0.0         1.0
1       1.0       0.0       0.0         1.0         0.0         0.0
2       0.0       0.0       1.0         0.0         0.0         1.0
3       1.0       0.0       0.0         0.0         0.0         1.0
4       0.0       0.0       1.0         0.0         0.0         1.0

## 4. Boolean Columns

The `Sex` column only contains 2 values: `male` and `female`. Build a custom transformers that is initialized with one of the values and returns a boolean column with values of `True` when that value is found and `False` otherwise.

In [22]:
class TrueFalseTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, flag):
        self.flag = flag
    
    def transform(self, X, *_):
        return X == self.flag

    def fit(self, X, *_):
        return self

In [23]:
gender_pipe = make_pipeline(ColumnSelector('Sex'),
                            TrueFalseTransformer('male'))

gender_pipe.fit_transform(df.head())

Sex
0   True
1  False
2  False
3  False
4   True

## 5. Fare

The `Fare` attribute can be scaled using one of the scalers from the preprocessing module. 

In [24]:
fare_pipe = make_pipeline(ColumnSelector('Fare'),
                          StandardScaler())

fare_pipe.fit_transform(df.head())

array([[-0.81614059],
       [ 1.53034706],
       [-0.79140535],
       [ 0.86402362],
       [-0.78682475]])

## 6. Union

Use the `make_union` function from the `sklearn.pipeline` modeule to combine all the pipes you have created.

In [25]:
union = make_union(age_pipe,
                   one_hot_pipe,
                   gender_pipe,
                   fare_pipe)

union.fit_transform(df.head())

array([[-1.50516598,  0.        ,  1.        ,  0.        ,  1.        ,
         1.        , -0.81614059],
       [ 1.11251398,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  1.53034706],
       [-0.85074599,  0.        ,  1.        ,  0.        ,  1.        ,
         0.        , -0.79140535],
       [ 0.62169899,  1.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.86402362],
       [ 0.62169899,  0.        ,  1.        ,  0.        ,  1.        ,
         1.        , -0.78682475]])

In [26]:
X = df[[u'Pclass', u'Sex', u'Age', u'SibSp', u'Parch', u'Fare', u'Embarked']]
y = df[u'Survived']

X.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

In [27]:
X = union.fit_transform(X)


AttributeError: 'numpy.ndarray' object has no attribute 'head'

The union you have created is a complete pre-processing pipeline that takes the original titanic dataset and extracts a bunch of features out of it. The last step of this process is to persist the `union` object to disk, so that it can be used again later. The following lines achieve this:

In [28]:
import dill
import gzip

with gzip.open('../../assets/datasets/union.dill.gz', 'w') as fout:
    dill.dump(union, fout)

## Bonus

Can you think of a way to engineer an additional boolean feature that keeps track whethere the person is travelling alone or with family?

In [ ]:
df['Family'] = (df['Parch'] > 0 ) & (df['SibSp'] > 0)